### ISSUE TITLE
Setup authentication and authorization acess

### ISSUE THREAD

**Issue by PDavor** [chingu-voyages/v36-bears-team-13#23]
**__Task Description__**
In navigation:

- [ ] show login and register only when the user isn't logged in
- [ ] show log out when the user is logged in

Page access:
- [ ] allow access to create ad page only for users with the role of nanny
- [ ] allow only not logged in users access to log in and register pages
